name: Actions Test
on: push

jobs:
  run:
    name: Lint with ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm install

      - name: Update source code
        run: ./action.js
        shell: bash

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Jim Nielsen
          author_email: jimniels@gmail.com
          message: "Test commit message"
          add: "*.json"
